### ISSUE TITLE
Parts Pending Return

### ISSUE THREAD

**Issue by henry1000** [filipp/gsxlib#41]
Hello,

I'm using the following code to get the Parts Pending Return List:

$info = $gsx->partsPendingReturn($repairData = null);
print_r($info);

But it is returning the following error:

Fatal error: Uncaught exception 'GsxException' with message 'SOAP-ERROR: Encoding: object has no 'serialNumbers' property' in /Users/admin/Sites/gsx/gsxlib.php:558 Stack trace: #0 /Users/admin/Sites/gsx/gsxlib.php(337): GsxLib->request(Array) #1 /Users/admin/Sites/gsx/index.php(136): GsxLib->partsPendingReturn(NULL) #2 {main} thrown in /Users/admin/Sites/gsx/gsxlib.php on line 558

Am I calling the method correctly?

- Henry

**Comment by henry1000** [comment]
Hello, 

Any tip on how to solve this?

Henry

**Comment by DjCtrlAltDel** [comment]
You have to specify $repairData
https://gsxwsut.apple.com/apidocs/it/html/WSReference.html?user=asp
Returns->partsPendingReturn
You are sending request with NULL value. It is supposed to have multiple:


ParameterDescriptionTypeMax LengthRequired?repairTypeRepair Type for which
parts have to be searched.String2NorepairStatusRepair Status for which
parts have to be searched.String2NopurchaseOrderNumberPurchase order number
String35NosroNumberRepair numberString12NorepairConfirmationNumberConfirmation
numberString15NoserialNumbers*Serial
numbersSerialNumbers[]NANoshipToCodeShip-to
codeString10NocustomerFirstNameCustomer's first nameString96No
customerLastNameCustomer's last nameString96NocustomerEmailAddressCustomer's
email addressString256NocreatedFromDateThe order creation start date. The
parts that are pending return will be searched during the given time
period, based on the order creation date.String†NocreatedToDateThe order
creation end date.String†NowarrantyTypeWarranty type. Expected values are
IW or OW.String2NokbbSerialNumberFlagExpected values are Y or N.String1No
comptiaCodecomptia CodeString3No

Also you have a hint in returned error







2015-03-17 12:39 GMT+01:00 Henrique Sousa <notifications@github.com>:

> Hello,
>
> Any tip on how to solve this?
>
> Henry
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/filipp/gsxlib/issues/41#issuecomment-82296917>.
>



-- 

*Serdecznie Pozdrawiam B. K.*

**Comment by henry1000** [comment]
Hello,

But if I give specific arguments I wont be getting all the Parts Pending Return, only a few right?

Henry

**Comment by filipp** [comment]
You must give at least one search parameter. What you probably want is all the pending parts for your ship-to:

```php

$gsx->partsPendingReturn(array('shipToCode' => 'yourshipto'));

```

**Comment by henry1000** [comment]
Hello filipp,

That is exactly what I'm searching for, after replacing the code with yours, it is displaying a very similar error.

Fatal error: Uncaught exception 'GsxException' with message 'SOAP-ERROR: Encoding: object has no 'serialNumbers' property' in /Users/admin/Sites/gsx/gsxlib.php:558 Stack trace: #0 /Users/admin/Sites/gsx/gsxlib.php(337): GsxLib->request(Array) #1 /Users/admin/Sites/gsx/index.php(136): GsxLib->partsPendingReturn(Array) #2 {main} thrown in /Users/admin/Sites/gsx/gsxlib.php on line 558

Any tip on how to solve this?

- Henry
