### ISSUE TITLE
Fatal error: Uncaught SoapFault exception: [WSDL] SOAP-ERROR

### ISSUE THREAD

**Issue by TheAdmiral926** [filipp/gsxlib#46]
Hello, 
Based off your example code on the main page I created this bit of php 
```
<?php

  include 'gsxlib/gsxlib.php';
  $_ENV['GSX_CERT'] = '/Library/Server/Web/Data/Sites/GSXAPI/Certs/cert.pem';
  $_ENV['GSX_KEYPASS'] = 'password';
  $serialnumber = 'W80245TIATN';
  $sold_to = '00000';
  $username = 'email@gmail.com';
  $gsx = GsxLib::getInstance($sold_to, $username);
  $info = $gsx->warrantyStatus($serialnumber);
  echo $info->productDescription;

?>
```
but when I try to run it I receive this error
```
Fatal error: Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://gsxapiut.apple.com/wsdl/amAsp/gsx-amAsp.wsdl' : 
failed to load external entity "https://gsxapiut.apple.com/wsdl/amAsp/gsx-amAsp.wsdl" in /Library/Server/Web/Data/Sites/GSXAPI/gsxlib/gsxlib.php:104 
Stack trace: #0 /Library/Server/Web/Data/Sites/GSXAPI/gsxlib/gsxlib.php(104): SoapClient->SoapClient('https://gsxapiu...', Array)
#1 /Library/Server/Web/Data/Sites/GSXAPI/gsxlib/gsxlib.php(41): GsxLib->__construct('44086', 'email@...', 'ut', 'am', 'CT') 
#2 /Library/Server/Web/Data/Sites/GSXAPI/index.php(9): GsxLib::getInstance('44086', 'email@...') 
#3 {main} thrown in /Library/Server/Web/Data/Sites/GSXAPI/gsxlib/gsxlib.php on line 104
```
Any ideas as to why? Thanks.

**Comment by TheAdmiral926** [comment]
Never mind, it seems this error was due to Apple not applying the certs or whitelisting the IP in a timely manner, I came back after the weekend and suddenly it works. Closing issue.
